fix: semver throwing error
The package is currently throwing the following error:
`Failed to construct transformer:  TypeError: semver is not a function`

It's simply because of the way `semver` is [being used](https://www.npmjs.com/package/semver), this should fix that.